import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import AuthProvider from "@/context/AuthContext";
import ToasterContext from "@/context/ToasterContext";

import "@/styles/globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
	return (
		<html lang="en">
			<body>
				<div className="main">
					<div className="gradient" />
				</div>

				<AuthProvider>
					<ToasterContext />
					<main className="app">
						<NavBar />
						{children}
						<Footer />
					</main>
				</AuthProvider>
			</body>
		</html>
	);
};

export default RootLayout;
